import type { IndustryRequirements, RequirementCategory } from '~/types'

// Common requirements applicable to all industries
const commonRequirements: RequirementCategory[] = [
  {
    id: 'user-auth',
    title: 'User Authentication & Authorization',
    description: 'How users will sign in and access your application securely.',
    items: [
      { id: 'email-auth', label: 'Email/Password Authentication', type: 'checkbox',
        description: 'Users create accounts with their email and a password. Standard login for most applications.' },
      { id: 'social-auth', label: 'Social Login (Google, Facebook, etc.)', type: 'checkbox',
        description: 'Users sign in with their existing Google, Facebook, Apple, or other social accounts — no need to remember a new password.' },
      { id: 'two-factor', label: 'Two-Factor Authentication (2FA)', type: 'checkbox',
        description: 'Adds an extra layer of security. After entering their password, users receive a code via SMS or authenticator app to confirm their identity.' },
      { id: 'sso', label: 'Single Sign-On (SSO)', type: 'checkbox',
        description: 'Users log in once and gain access to multiple related systems without signing in again. Common for enterprise/corporate applications.' },
      { id: 'role-based', label: 'Role-Based Access Control', type: 'checkbox',
        description: 'Different users see different features based on their role (e.g., Admin, Manager, Viewer). Ensures the right people access the right data.' },
      { id: 'user-profiles', label: 'User Profile Management', type: 'checkbox',
        description: 'Users can view and edit their personal information, upload a profile photo, update contact details, and manage preferences.' },
    ],
  },
  {
    id: 'ui-ux',
    title: 'User Interface & Experience',
    description: 'How your application will look and feel to users across devices.',
    items: [
      { id: 'responsive', label: 'Responsive Design (Mobile, Tablet, Desktop)', type: 'checkbox', required: true,
        description: 'Your application automatically adjusts its layout to look great on phones, tablets, and desktop computers.' },
      { id: 'dark-mode', label: 'Dark Mode Support', type: 'checkbox',
        description: 'A darker color theme option that reduces eye strain, especially in low-light environments. Popular with many modern apps.' },
      { id: 'accessibility', label: 'Accessibility Compliance (WCAG)', type: 'checkbox',
        description: 'Makes your app usable by people with disabilities — screen reader support, keyboard navigation, proper color contrast, and more.' },
      { id: 'multilingual', label: 'Multi-language Support', type: 'checkbox',
        description: 'Your application can be viewed in multiple languages, allowing international users to use it in their preferred language.' },
      { id: 'custom-branding', label: 'Custom Branding & Theming', type: 'checkbox',
        description: 'Your logo, brand colors, fonts, and visual identity are woven throughout the application for a professional, cohesive look.' },
    ],
  },
  {
    id: 'data-management',
    title: 'Data Management',
    description: 'How information is stored, searched, and organized in your application.',
    items: [
      { id: 'crud', label: 'Create, Read, Update, Delete Operations', type: 'checkbox',
        description: 'Users can create new records, view them, edit existing ones, and delete them when needed — the foundation of most data-driven apps.' },
      { id: 'search', label: 'Advanced Search & Filtering', type: 'checkbox',
        description: 'Users can quickly find specific items using keywords, filters (date, category, status), and sorting options.' },
      { id: 'import-export', label: 'Data Import/Export (CSV, Excel, PDF)', type: 'checkbox',
        description: 'Upload data from spreadsheets into your app, or download your data as files for reporting, backup, or sharing.' },
      { id: 'file-upload', label: 'File Upload & Management', type: 'checkbox',
        description: 'Users can upload documents, images, PDFs, or other files and manage them within the application (view, download, delete).' },
      { id: 'data-validation', label: 'Data Validation & Sanitization', type: 'checkbox',
        description: 'Ensures data entered is correct and safe — e.g., email fields must contain a valid email, and harmful code is blocked.' },
    ],
  },
  {
    id: 'notifications',
    title: 'Notifications & Communications',
    description: 'How your application keeps users informed and engaged.',
    items: [
      { id: 'email-notif', label: 'Email Notifications', type: 'checkbox',
        description: 'Users receive updates, alerts, and reminders directly to their email inbox — e.g., "Your order has shipped" or "New message received."' },
      { id: 'sms-notif', label: 'SMS Notifications', type: 'checkbox',
        description: 'Important alerts are sent as text messages to users\' phones — useful for time-sensitive or urgent notifications.' },
      { id: 'push-notif', label: 'Push Notifications', type: 'checkbox',
        description: 'Pop-up alerts appear on users\' devices (phone or browser) even when they\'re not actively using the app.' },
      { id: 'in-app-notif', label: 'In-App Notifications', type: 'checkbox',
        description: 'A notification bell or inbox inside the app where users can see recent updates, messages, and alerts.' },
    ],
  },
  {
    id: 'security',
    title: 'Security Features',
    description: 'Protecting your application and user data from threats.',
    items: [
      { id: 'encryption', label: 'Data Encryption (At Rest & In Transit)', type: 'checkbox',
        description: 'All sensitive data is scrambled and unreadable to unauthorized parties — both when stored and when sent over the internet.' },
      { id: 'gdpr', label: 'GDPR Compliance', type: 'checkbox',
        description: 'Ensures your app respects user privacy rights as required by European law — consent, data deletion, data portability, and more.' },
      { id: 'audit-logs', label: 'Audit Logs & Activity Tracking', type: 'checkbox',
        description: 'A record of who did what and when — useful for accountability, debugging, and compliance. E.g., "User X deleted record Y at 3:45 PM."' },
      { id: 'backup', label: 'Automated Backup & Recovery', type: 'checkbox',
        description: 'Your data is automatically backed up regularly, so if something goes wrong (server crash, accidental deletion), it can be restored.' },
      { id: 'ddos', label: 'DDoS Protection', type: 'checkbox',
        description: 'Protects your application from malicious attacks that try to overwhelm and crash your servers by flooding them with fake traffic.' },
    ],
  },
  {
    id: 'integrations',
    title: 'Third-Party Integrations',
    description: 'Connecting your application to external services and tools.',
    items: [
      { id: 'payment', label: 'Payment Gateway (Stripe, PayPal, Mobile Money)', type: 'checkbox',
        description: 'Accept payments from users directly in your app via credit cards, PayPal, MTN MoMo, or other payment methods.' },
      { id: 'analytics', label: 'Analytics (Google Analytics, Mixpanel)', type: 'checkbox',
        description: 'Track how users interact with your app — which pages they visit, how long they stay, and where they drop off — to improve the experience.' },
      { id: 'crm-integration', label: 'CRM Integration', type: 'checkbox',
        description: 'Connect your app to a Customer Relationship Management system (like Salesforce or HubSpot) to manage customer relationships.' },
      { id: 'email-marketing', label: 'Email Marketing (Mailchimp, SendGrid)', type: 'checkbox',
        description: 'Send bulk emails, newsletters, or marketing campaigns to your users through services like Mailchimp or SendGrid.' },
      { id: 'api-integrations', label: 'Custom API Integrations', type: 'checkbox',
        description: 'Connect your app to any external service or system — weather data, mapping, social media feeds, government databases, etc.' },
    ],
  },
  {
    id: 'admin',
    title: 'Admin Features',
    description: 'Tools for administrators to manage and monitor the application.',
    items: [
      { id: 'dashboard', label: 'Admin Dashboard', type: 'checkbox',
        description: 'A control panel for administrators showing key metrics, recent activity, and quick actions to manage the entire application.' },
      { id: 'user-management', label: 'User Management', type: 'checkbox',
        description: 'Admins can view, edit, suspend, or delete user accounts, assign roles, and reset passwords from a central interface.' },
      { id: 'content-management', label: 'Content Management System (CMS)', type: 'checkbox',
        description: 'A user-friendly editor for creating, editing, and publishing content (articles, pages, images) without needing to write code.' },
      { id: 'reporting', label: 'Reports & Analytics', type: 'checkbox',
        description: 'Generate detailed reports and charts about usage, revenue, user activity, or any custom metric — exportable to PDF or Excel.' },
      { id: 'settings', label: 'System Settings & Configuration', type: 'checkbox',
        description: 'A settings panel where admins can configure application behavior — toggle features, set global preferences, manage integrations.' },
    ],
  },
]

// Industry-specific requirements
export const industryRequirements: IndustryRequirements = {
  HEALTHCARE: [
    ...commonRequirements,
    {
      id: 'healthcare-specific',
      title: 'Healthcare-Specific Features',
      description: 'Specialized tools for medical and healthcare applications.',
      items: [
        { id: 'hipaa', label: 'HIPAA Compliance', type: 'checkbox', required: true,
          description: 'Ensures your app meets U.S. healthcare privacy and security regulations. Required if handling any patient health information.' },
        { id: 'ehr', label: 'Electronic Health Records (EHR) Integration', type: 'checkbox',
          description: 'Connect with existing hospital/clinic systems to access and update patient medical records digitally.' },
        { id: 'appointment', label: 'Appointment Scheduling System', type: 'checkbox',
          description: 'Patients can book, reschedule, or cancel appointments with doctors. Admins manage availability and send reminders.' },
        { id: 'telemedicine', label: 'Telemedicine/Video Consultation', type: 'checkbox',
          description: 'Built-in video calling that allows doctors and patients to conduct remote consultations securely.' },
        { id: 'prescription', label: 'E-Prescription Management', type: 'checkbox',
          description: 'Doctors can digitally prescribe medications, which are sent directly to the patient\'s preferred pharmacy.' },
        { id: 'patient-portal', label: 'Patient Portal', type: 'checkbox',
          description: 'A secure area where patients can view their medical history, lab results, appointments, and communicate with their doctor.' },
        { id: 'lab-integration', label: 'Laboratory System Integration', type: 'checkbox',
          description: 'Connect with lab systems so test results are automatically sent to the patient\'s record and the doctor is notified.' },
        { id: 'billing', label: 'Medical Billing & Insurance Claims', type: 'checkbox',
          description: 'Generate and submit insurance claims, track payments, and manage patient billing — often tied to insurance coding systems.' },
      ],
    },
  ],
  
  FINANCE: [
    ...commonRequirements,
    {
      id: 'finance-specific',
      title: 'Finance-Specific Features',
      description: 'Essential features for financial, banking, and fintech applications.',
      items: [
        { id: 'pci-dss', label: 'PCI-DSS Compliance', type: 'checkbox', required: true,
          description: 'Security standard for handling credit card information. Required if your app processes, stores, or transmits card data.' },
        { id: 'kyc', label: 'KYC/AML Verification', type: 'checkbox',
          description: 'Verify user identities (Know Your Customer) and monitor for suspicious activity (Anti-Money Laundering) — required for financial services.' },
        { id: 'transactions', label: 'Transaction Management', type: 'checkbox',
          description: 'Track, process, and display financial transactions — deposits, withdrawals, transfers — with full audit trails.' },
        { id: 'multi-currency', label: 'Multi-Currency Support', type: 'checkbox',
          description: 'Display and process amounts in multiple currencies with live exchange rates — essential for international finance.' },
        { id: 'accounting', label: 'Accounting & Bookkeeping', type: 'checkbox',
          description: 'Track income, expenses, assets, and liabilities. Generate ledgers, journals, and financial statements.' },
        { id: 'invoicing', label: 'Invoicing & Billing System', type: 'checkbox',
          description: 'Create, send, and track invoices. Support recurring billing, late fees, and automated payment reminders.' },
        { id: 'financial-reporting', label: 'Financial Reports & Statements', type: 'checkbox',
          description: 'Generate balance sheets, income statements, cash flow reports, and custom financial analytics.' },
        { id: 'fraud-detection', label: 'Fraud Detection & Prevention', type: 'checkbox',
          description: 'AI-powered monitoring that flags suspicious transactions, unusual login patterns, or potential identity theft.' },
      ],
    },
  ],
  
  ECOMMERCE: [
    ...commonRequirements,
    {
      id: 'ecommerce-specific',
      title: 'E-Commerce-Specific Features',
      description: 'Everything needed to run an online store.',
      items: [
        { id: 'product-catalog', label: 'Product Catalog Management', type: 'checkbox', required: true,
          description: 'Organize products with images, descriptions, prices, categories, and variations (size, color, etc.). Easy for admins to add/edit.' },
        { id: 'shopping-cart', label: 'Shopping Cart', type: 'checkbox', required: true,
          description: 'Users add products to a cart, adjust quantities, and review their selections before checkout.' },
        { id: 'checkout', label: 'Checkout Process', type: 'checkbox', required: true,
          description: 'A streamlined flow where users enter shipping details, choose payment method, and confirm their order.' },
        { id: 'inventory', label: 'Inventory Management', type: 'checkbox',
          description: 'Automatically track stock levels, alert when items are running low, and prevent overselling.' },
        { id: 'order-tracking', label: 'Order Tracking & Management', type: 'checkbox',
          description: 'Customers can see their order status (Processing → Shipped → Delivered). Admins manage fulfillment.' },
        { id: 'reviews', label: 'Product Reviews & Ratings', type: 'checkbox',
          description: 'Customers leave star ratings and written reviews on products, helping other shoppers make decisions.' },
        { id: 'wishlist', label: 'Wishlist Functionality', type: 'checkbox',
          description: 'Users save products they\'re interested in for later — can share wishlists or get notified when items go on sale.' },
        { id: 'discounts', label: 'Discounts & Coupon Management', type: 'checkbox',
          description: 'Create promotional codes, seasonal sales, bundle deals, and loyalty discounts to drive purchases.' },
        { id: 'shipping', label: 'Shipping Integration', type: 'checkbox',
          description: 'Calculate shipping costs in real-time based on weight, location, and carrier rates. Generate shipping labels.' },
      ],
    },
  ],
  
  EDUCATION: [
    ...commonRequirements,
    {
      id: 'education-specific',
      title: 'Education-Specific Features',
      description: 'Features for online learning platforms and educational institutions.',
      items: [
        { id: 'lms', label: 'Learning Management System (LMS)', type: 'checkbox',
          description: 'A complete platform for delivering courses — students enroll, access materials, submit work, and track progress.' },
        { id: 'course-management', label: 'Course Creation & Management', type: 'checkbox',
          description: 'Instructors build courses with modules, lessons, quizzes, and resources. Organize by difficulty or topic.' },
        { id: 'student-portal', label: 'Student Portal', type: 'checkbox',
          description: 'A personalized dashboard for students showing enrolled courses, progress, grades, upcoming deadlines, and resources.' },
        { id: 'video-lessons', label: 'Video Lessons & Streaming', type: 'checkbox',
          description: 'Host and stream video lectures with playback controls — pause, rewind, adjust speed. Supports embedded YouTube or self-hosted.' },
        { id: 'assignments', label: 'Assignments & Submissions', type: 'checkbox',
          description: 'Instructors create assignments with deadlines. Students upload files or type responses. Instructors review and give feedback.' },
        { id: 'quizzes', label: 'Quizzes & Assessments', type: 'checkbox',
          description: 'Multiple-choice, fill-in-the-blank, or essay questions. Auto-grading for objective questions, manual for essays.' },
        { id: 'grading', label: 'Grading System', type: 'checkbox',
          description: 'Assign grades (A–F, percentage, or custom scales). Calculate overall course grades and generate report cards.' },
        { id: 'certificates', label: 'Certificate Generation', type: 'checkbox',
          description: 'Automatically generate downloadable certificates when students complete a course — with their name, course title, and date.' },
        { id: 'live-classes', label: 'Live Virtual Classroom', type: 'checkbox',
          description: 'Real-time video sessions where instructors teach live, share screens, and interact with students via chat or hand-raise.' },
      ],
    },
  ],
  
  REAL_ESTATE: [
    ...commonRequirements,
    {
      id: 'realestate-specific',
      title: 'Real Estate-Specific Features',
      description: 'Features for property listings, agent management, and buyer/seller tools.',
      items: [
        { id: 'property-listings', label: 'Property Listings Management', type: 'checkbox', required: true,
          description: 'Add, edit, and manage property listings with photos, descriptions, prices, floor plans, and key features.' },
        { id: 'map-integration', label: 'Map & Location Integration', type: 'checkbox',
          description: 'Show properties on an interactive map (Google Maps). Users can zoom, click pins, and see nearby amenities.' },
        { id: 'virtual-tours', label: 'Virtual Tours & 360° Views', type: 'checkbox',
          description: 'Immersive walkthroughs where users explore properties virtually using 360° photos or 3D models.' },
        { id: 'search-filters', label: 'Advanced Property Search Filters', type: 'checkbox',
          description: 'Search by price range, number of bedrooms, property type, location, amenities, and more.' },
        { id: 'agent-portal', label: 'Agent Portal', type: 'checkbox',
          description: 'Real estate agents have a dedicated dashboard to manage their listings, leads, appointments, and performance.' },
        { id: 'mortgage-calc', label: 'Mortgage Calculator', type: 'checkbox',
          description: 'Help buyers estimate monthly payments based on property price, down payment, interest rate, and loan term.' },
        { id: 'scheduling', label: 'Property Viewing Scheduling', type: 'checkbox',
          description: 'Buyers book in-person or virtual property viewings. Agents manage their calendar and confirm appointments.' },
        { id: 'crm', label: 'Lead Management CRM', type: 'checkbox',
          description: 'Track potential buyers/sellers, log interactions, set follow-up reminders, and manage the sales pipeline.' },
      ],
    },
  ],
  
  LOGISTICS: [
    ...commonRequirements,
    {
      id: 'logistics-specific',
      title: 'Logistics-Specific Features',
      description: 'Features for shipping, fleet management, and supply chain operations.',
      items: [
        { id: 'shipment-tracking', label: 'Real-Time Shipment Tracking', type: 'checkbox', required: true,
          description: 'Customers and admins can track packages in real-time with GPS updates, estimated delivery times, and status milestones.' },
        { id: 'route-optimization', label: 'Route Optimization', type: 'checkbox',
          description: 'AI calculates the most efficient delivery routes to save fuel and time — considers traffic, weather, and delivery windows.' },
        { id: 'fleet-management', label: 'Fleet Management', type: 'checkbox',
          description: 'Monitor all vehicles in your fleet — location, fuel levels, maintenance schedules, driver assignments, and performance.' },
        { id: 'warehouse', label: 'Warehouse Management System', type: 'checkbox',
          description: 'Manage inventory storage, picking, packing, and dispatch. Track stock locations within the warehouse.' },
        { id: 'driver-app', label: 'Driver Mobile App', type: 'checkbox',
          description: 'A companion app for drivers showing assigned deliveries, routes, navigation, and proof-of-delivery capture.' },
        { id: 'barcode', label: 'Barcode/QR Code Scanning', type: 'checkbox',
          description: 'Scan packages using phone cameras or handheld scanners for quick check-in, check-out, and tracking updates.' },
        { id: 'shipping-labels', label: 'Automated Shipping Labels', type: 'checkbox',
          description: 'Generate shipping labels automatically with recipient details, barcode, and carrier information — ready to print.' },
        { id: 'delivery-proof', label: 'Proof of Delivery', type: 'checkbox',
          description: 'Capture a signature, photo, or timestamp when a delivery is completed — stored as evidence and sent to the customer.' },
      ],
    },
  ],
}

// Default/fallback requirements for industries not specifically defined
export const getIndustryRequirements = (industry: string): RequirementCategory[] => {
  return industryRequirements[industry] || commonRequirements
}
